import Head from "next/head";
import Navbar from "../components/Navbar";
import Hero from "../components/Hero";
import About from "../components/About";
import WhatDo from "../components/WhatDo";
import Skills from "../components/Skills";
import Work from "../components/Work";
import Contact from "../components/Contact";


export default function Home() {
  return (
    <div>
      <Head>
        <title>Shohidul Islam || Protfolio </title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <header>
        <Navbar/>
      </header>

      <main>
       <Hero/>
       <About/>
       <WhatDo/>
       <Skills/>
       <Work/>
       <Contact/>
      </main>

    </div>
   
  )
}
