import Head from "next/head";
import Navbar from "../components/Navbar";
import Image from "next/image";
import Hero from "../components/Hero";


export default function Home() {
  return (
    <div>
      <Head>
        <title>Shohidul Islam | Protfolio </title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <header>
        <Navbar/>
      </header>

      <main>
       <Hero/>
      </main>

    </div>
   
  )
}
